# Generated by Django 3.1.2 on 2021-03-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_craigslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
